title = "Introduction to Go"

[author]
name = "Adnaan Badr"
email = "badr.adnaan@gmail.com"
github = "adnaan"

[[modules]]
name = "Data types"

[[modules.lessons]]
name = "Hello world"
index = "data_types/hello_world/index.md"

[[modules.lessons]]
name = "Variables & Constants"
index = ""

[[modules]]
name = "Functions"
index = ""

[[modules.lessons]]
name = "Simple function"
index = ""

[[modules.lessons]]
name = "Multipe return values"
index = ""
